# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Notice Location' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'Alamofire',
  :git => 'https://github.com/Alamofire/Alamofire.git'

  pod 'SwiftyJSON'
  pod 'GoogleMaps'
  pod 'GooglePlaces'
  pod 'SDWebImage', '~> 3.8'
  pod 'PKHUD', '~> 4.0'
  # Pods for Notice Location

  target 'Notice LocationTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Notice LocationUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
